local withTests = require('minitest')
local assert = require('luassert')

math.randomseed(os.time())

withTests(function(c)
    c:describe("level 1",function(c)
        c:describe("level 2",function(c)
            c:it("testl",function()
                assert.same(1,5)
            end)
        end)
        c:it("test23",function()
            assert.same(1,6)
        end)
    end)
    local coro = coroutine.wrap(function()
        c:describe("futurized",function(c)
            c:it("let's resume this later",function(c)
                print("\nin the test")
                return function()
                    success = coroutine.yield()
                    print("\nback in the test")
                    if success then 
                        print('we succeed yay')
                    else
                        print('we now fail')
                        error('fail')
                    end
                end
            end)
        end)
    end)
    coro()
    c:describe("something",function(c)
        c:it("test1",function(c)
            assert.same(1,1)
        end)
        c:it("test2",function(c)
            assert.same(1,2)
        end)
    end)
    coro(math.random(1,10)>5)
end)
