local withTests = require('minitest')
local assert = require('luassert')

withTests(function()
    describe("level 1",function()
        describe("level 2",function()
            it("testl",function()
                assert.same(1,5)
            end)
        end)
        it("test23",function()
            assert.same(1,6)
        end)
    end)
    describe("something",function()
        it("test1",function()
            assert.same(1,1)
        end)
        it("test2",function()
            assert.same(1,2)
        end)
    end)
    local coro = coroutine.wrap(function()
        describe("futurized",function()
            it("let's resume this later",function()
                print("in the test")
                return function()
                    success = coroutine.yield()
                    print("back in the test")
                    if success then 
                        print('we succeed yay')
                    else
                        error('fail')
                    end
                end
            end)
        end)
    end)
    coro()
    coro(true)
end)
